# Generated by Django 5.1.2 on 2024-10-24 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('GoalName', models.CharField(max_length=255)),
                ('TargetValue', models.IntegerField()),
                ('TargetDate', models.DateField()),
                ('Reacurring', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('InvestmentName', models.CharField(max_length=255)),
                ('CurrentValue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('AmountInvested', models.IntegerField()),
                ('CurrentValue', models.IntegerField(blank=True, null=True)),
                ('InvestmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.investmentname')),
            ],
        ),
        migrations.CreateModel(
            name='NetWorth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TotalAssets', models.IntegerField()),
                ('TotalLiabilities', models.IntegerField()),
                ('CreatedAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TransactionAmount', models.IntegerField()),
                ('CreatedAt', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('GoalName', models.CharField(max_length=255)),
                ('TargetValue', models.IntegerField()),
                ('TargetDate', models.DateField()),
                ('Reacurring', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SubCategory', models.CharField(max_length=255, unique=True)),
                ('SpendingLimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=255)),
                ('SpendingLimit', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyInvestmentValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TotalValue', models.IntegerField()),
                ('CreatedAt', models.DateField()),
                ('InvestmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.investmentname')),
            ],
        ),
        migrations.CreateModel(
            name='ReacurringInvestmentPurchase',
            fields=[
                ('investmentpurchase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.investmentpurchase')),
                ('DueDate', models.DateField()),
            ],
            bases=('base.investmentpurchase',),
        ),
        migrations.CreateModel(
            name='ReacurringTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.transaction')),
                ('DueDate', models.DateField(blank=True, null=True)),
            ],
            bases=('base.transaction',),
        ),
        migrations.AddField(
            model_name='investmentpurchase',
            name='SavingsGoal',
            field=models.ManyToManyField(blank=True, to='base.savingsgoal'),
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('IncomeSource', models.CharField(max_length=255)),
                ('Value', models.IntegerField()),
                ('Reacurring', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('SavingsGoal', models.ManyToManyField(blank=True, null=True, to='base.savingsgoal')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Vendor', models.CharField(max_length=255)),
                ('SpendingLimit', models.IntegerField(blank=True, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='Vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.vendor'),
        ),
    ]
