# Generated by Django 5.1.2 on 2024-10-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_transaction_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='SubCategory',
        ),
    ]
