# Generated by Django 5.1.2 on 2024-10-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='CreatedAt',
            field=models.DateField(),
        ),
    ]
