# Generated by Django 5.1.2 on 2024-10-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_transaction_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='CreatedAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
